site_name: NetBox Documentation
site_dir: netbox/project-static/docs
site_url: https://docs.netbox.dev/
repo_name: netbox-community/netbox
repo_url: https://github.com/netbox-community/netbox
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to Light Mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import os
            - import django
            - os.chdir('netbox/')
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "netbox.settings")
            - django.setup()
          rendering:
            heading_level: 3
            members_order: source
            show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: false
            show_source: false
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/netbox-community/netbox
    - icon: fontawesome/brands/slack
      link: https://netdev.chat/
extra_css:
    - extra.css
markdown_extensions:
    - admonition
    - attr_list
    - markdown_include.include:
        base_path: 'docs/'
        headingOffset: 1
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
nav:
    - Introduction: 'introduction.md'
    - Installation & Upgrade:
        - Installing NetBox: 'installation/index.md'
        - 1. PostgreSQL: 'installation/1-postgresql.md'
        - 2. Redis: 'installation/2-redis.md'
        - 3. NetBox: 'installation/3-netbox.md'
        - 4. Gunicorn: 'installation/4-gunicorn.md'
        - 5. HTTP Server: 'installation/5-http-server.md'
        - 6. LDAP (Optional): 'installation/6-ldap.md'
        - Upgrading NetBox: 'installation/upgrading.md'
    - Getting Started:
        - Planning: 'getting-started/planning.md'
        - Populating Data: 'getting-started/populating-data.md'
    - Configuration:
        - Configuring NetBox: 'configuration/index.md'
        - Required Settings: 'configuration/required-settings.md'
        - Optional Settings: 'configuration/optional-settings.md'
        - Dynamic Settings: 'configuration/dynamic-settings.md'
        - Error Reporting: 'configuration/error-reporting.md'
        - Remote Authentication: 'configuration/remote-authentication.md'
    - Customization:
        - Custom Fields: 'customization/custom-fields.md'
        - Custom Validation: 'customization/custom-validation.md'
        - Custom Links: 'models/extras/customlink.md'
        - Export Templates: 'customization/export-templates.md'
        - Custom Scripts: 'customization/custom-scripts.md'
        - Reports: 'customization/reports.md'
    - Additional Features:
        - Change Logging: 'additional-features/change-logging.md'
        - Context Data: 'models/extras/configcontext.md'
        - Journaling: 'additional-features/journaling.md'
        - NAPALM: 'additional-features/napalm.md'
        - Prometheus Metrics: 'additional-features/prometheus-metrics.md'
        - Tags: 'models/extras/tag.md'
        - Webhooks: 'additional-features/webhooks.md'
    - Plugins:
        - Using Plugins: 'plugins/index.md'
        - Developing Plugins:
            - Getting Started: 'plugins/development/index.md'
            - Models: 'plugins/development/models.md'
            - Views: 'plugins/development/views.md'
            - Navigation: 'plugins/development/navigation.md'
            - Templates: 'plugins/development/templates.md'
            - Tables: 'plugins/development/tables.md'
            - Forms: 'plugins/development/forms.md'
            - Filters & Filter Sets: 'plugins/development/filtersets.md'
            - REST API: 'plugins/development/rest-api.md'
            - GraphQL API: 'plugins/development/graphql-api.md'
            - Background Tasks: 'plugins/development/background-tasks.md'
            - Exceptions: 'plugins/development/exceptions.md'
    - Administration:
        - Authentication:
            - Overview: 'administration/authentication/overview.md'
            - Microsoft Azure AD: 'administration/authentication/microsoft-azure-ad.md'
            - Okta: 'administration/authentication/okta.md'
        - Permissions: 'administration/permissions.md'
        - Error Reporting: 'administration/error-reporting.md'
        - Housekeeping: 'administration/housekeeping.md'
        - Replicating NetBox: 'administration/replicating-netbox.md'
        - NetBox Shell: 'administration/netbox-shell.md'
    - REST API:
        - Overview: 'rest-api/overview.md'
        - Filtering & Ordering: 'rest-api/filtering.md'
        - Authentication: 'rest-api/authentication.md'
    - GraphQL API:
        - Overview: 'graphql-api/overview.md'
    - Data Model:
        - Circuits:
            - Circuit: 'models/circuits/circuit.md'
            - Circuit Termination: 'models/circuits/circuittermination.md'
            - Circuit Type: 'models/circuits/circuittype.md'
            - Provider: 'models/circuits/provider.md'
            - Provider Network: 'models/circuits/providernetwork.md'
        - DCIM:
            - Cable: 'models/dcim/cable.md'
            - CablePath: 'models/dcim/cablepath.md'
            - CableTermination: 'models/dcim/cabletermination.md'
            - ConsolePort: 'models/dcim/consoleport.md'
            - ConsolePortTemplate: 'models/dcim/consoleporttemplate.md'
            - ConsoleServerPort: 'models/dcim/consoleserverport.md'
            - ConsoleServerPortTemplate: 'models/dcim/consoleserverporttemplate.md'
            - Device: 'models/dcim/device.md'
            - DeviceBay: 'models/dcim/devicebay.md'
            - DeviceBayTemplate: 'models/dcim/devicebaytemplate.md'
            - DeviceRole: 'models/dcim/devicerole.md'
            - DeviceType: 'models/dcim/devicetype.md'
            - FrontPort: 'models/dcim/frontport.md'
            - FrontPortTemplate: 'models/dcim/frontporttemplate.md'
            - Interface: 'models/dcim/interface.md'
            - InterfaceTemplate: 'models/dcim/interfacetemplate.md'
            - InventoryItem: 'models/dcim/inventoryitem.md'
            - InventoryItemRole: 'models/dcim/inventoryitemrole.md'
            - InventoryItemTemplate: 'models/dcim/inventoryitemtemplate.md'
            - Location: 'models/dcim/location.md'
            - Manufacturer: 'models/dcim/manufacturer.md'
            - Module: 'models/dcim/module.md'
            - ModuleBay: 'models/dcim/modulebay.md'
            - ModuleBayTemplate: 'models/dcim/modulebaytemplate.md'
            - ModuleType: 'models/dcim/moduletype.md'
            - Platform: 'models/dcim/platform.md'
            - PowerFeed: 'models/dcim/powerfeed.md'
            - PowerOutlet: 'models/dcim/poweroutlet.md'
            - PowerOutletTemplate: 'models/dcim/poweroutlettemplate.md'
            - PowerPanel: 'models/dcim/powerpanel.md'
            - PowerPort: 'models/dcim/powerport.md'
            - PowerPortTemplate: 'models/dcim/powerporttemplate.md'
            - Rack: 'models/dcim/rack.md'
            - RackReservation: 'models/dcim/rackreservation.md'
            - RackRole: 'models/dcim/rackrole.md'
            - RearPort: 'models/dcim/rearport.md'
            - RearPortTemplate: 'models/dcim/rearporttemplate.md'
            - Region: 'models/dcim/region.md'
            - Site: 'models/dcim/site.md'
            - SiteGroup: 'models/dcim/sitegroup.md'
            - VirtualChassis: 'models/dcim/virtualchassis.md'
        - IPAM:
            - ASN: 'models/ipam/asn.md'
            - Aggregate: 'models/ipam/aggregate.md'
            - FHRPGroup: 'models/ipam/fhrpgroup.md'
            - FHRPGroupAssignment: 'models/ipam/fhrpgroupassignment.md'
            - IPAddress: 'models/ipam/ipaddress.md'
            - IPRange: 'models/ipam/iprange.md'
            - L2VPN: 'models/ipam/l2vpn.md'
            - L2VPNTermination: 'models/ipam/l2vpntermination.md'
            - Prefix: 'models/ipam/prefix.md'
            - RIR: 'models/ipam/rir.md'
            - Role: 'models/ipam/role.md'
            - RouteTarget: 'models/ipam/routetarget.md'
            - Service: 'models/ipam/service.md'
            - ServiceTemplate: 'models/ipam/servicetemplate.md'
            - VLAN: 'models/ipam/vlan.md'
            - VLANGroup: 'models/ipam/vlangroup.md'
            - VRF: 'models/ipam/vrf.md'
        - Tenancy:
            - Contact: 'models/tenancy/contact.md'
            - ContactAssignment: 'models/tenancy/contactassignment.md'
            - ContactGroup: 'models/tenancy/contactgroup.md'
            - ContactRole: 'models/tenancy/contactrole.md'
            - Tenant: 'models/tenancy/tenant.md'
            - TenantGroup: 'models/tenancy/tenantgroup.md'
        - Virtualization:
            - Cluster: 'models/virtualization/cluster.md'
            - ClusterGroup: 'models/virtualization/clustergroup.md'
            - ClusterType: 'models/virtualization/clustertype.md'
            - VMInterface: 'models/virtualization/vminterface.md'
            - VirtualMachine: 'models/virtualization/virtualmachine.md'
        - Wireless:
            - WirelessLAN: 'models/wireless/wirelesslan.md'
            - WirelessLANGroup: 'models/wireless/wirelesslangroup.md'
            - WirelessLink: 'models/wireless/wirelesslink.md'
    - Reference:
        - Conditions: 'reference/conditions.md'
        - Markdown: 'reference/markdown.md'
    - Development:
        - Introduction: 'development/index.md'
        - Getting Started: 'development/getting-started.md'
        - Style Guide: 'development/style-guide.md'
        - Models: 'development/models.md'
        - Adding Models: 'development/adding-models.md'
        - Extending Models: 'development/extending-models.md'
        - Signals: 'development/signals.md'
        - Application Registry: 'development/application-registry.md'
        - User Preferences: 'development/user-preferences.md'
        - Web UI: 'development/web-ui.md'
        - Release Checklist: 'development/release-checklist.md'
    - Release Notes:
        - Summary: 'release-notes/index.md'
        - Version 3.3: 'release-notes/version-3.3.md'
        - Version 3.2: 'release-notes/version-3.2.md'
        - Version 3.1: 'release-notes/version-3.1.md'
        - Version 3.0: 'release-notes/version-3.0.md'
        - Version 2.11: 'release-notes/version-2.11.md'
        - Version 2.10: 'release-notes/version-2.10.md'
        - Version 2.9: 'release-notes/version-2.9.md'
        - Version 2.8: 'release-notes/version-2.8.md'
        - Version 2.7: 'release-notes/version-2.7.md'
        - Version 2.6: 'release-notes/version-2.6.md'
        - Version 2.5: 'release-notes/version-2.5.md'
        - Version 2.4: 'release-notes/version-2.4.md'
        - Version 2.3: 'release-notes/version-2.3.md'
        - Version 2.2: 'release-notes/version-2.2.md'
        - Version 2.1: 'release-notes/version-2.1.md'
        - Version 2.0: 'release-notes/version-2.0.md'
